version: '3.8'
services:
  chat-widget-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wiseai-chat-widget-client
    ports:
      - "4180:80"
    restart: unless-stopped
