services:
  influxdb3-core:
    image: influxdb:3-core
    container_name: influxdb3-core
    ports:
      - "8181:8181"
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
    volumes:
      - ./data:/var/lib/influxdb3/data
      - ./plugins:/var/lib/influxdb3/plugins

  explorer:
    image: influxdata/influxdb3-ui:1.6.2
    container_name: influxdb3-explorer
    ports:
      - "8888:80"
    depends_on:
      - influxdb3-core
    command: ["--mode=admin"]
    environment:
      SESSION_SECRET_KEY: "change_me_to_a_long_random_string"
    volumes:
      - ./explorer-db:/db
      - ./explorer-config:/app-root/config:ro