services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_logmind
    restart: always

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - "${DB_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  back_end:
    build:
      context: ./back_end
      dockerfile: Dockerfile

    container_name: logmind_api

    restart: always

    env_file:
      - .env

    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DEBUG_MODE: ${DEBUG_MODE:-false}

    ports:
      - "5000:5000"
      - "5678:5678"

    volumes:
      - uploads_data:/app/storage/uploads

    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  uploads_data: