services:
  # rory-dataowner-0:
  #   image: shanelreyes/rory:dataowner
  #   container_name: rory-dataowner-0
  #   environment:
  #     - NODE_ID=rory-dataowner-0
  #     - CLIENT_PORT=3000
  #     - CLIENT_INDEX=0
  #     - CLIENT_ID=rory-client-0
  #     - CLIENT_IP_ADDR=rory-client-0
  #     - TASK_ID=${TASK_ID}
  #     - ALGORITHM=${ALGORITHM}
  #     - BATCH_ID=${BATCH_ID}
  #     - TRACE_ID=${TRACE_ID}
  #     - MAX_THREADS=${MAX_THREADS}
  #     - CUSTOM_PYTHON_PATH=/app
  #     - SOURCE_PATH=/rory/source
  #     - SINK_PATH=/rory/sink
  #     - LOG_PATH=/rory/log
  #   volumes:
  #     - /rory/rory-dataowner-0/source:/rory/source
  #     - /rory/rory-dataowner-0/sink:/rory/sink
  #     - /rory/rory-dataowner-0/log:/rory/log
  #   networks:
  #     - mictlanx
  #   deploy:
  #     placement:
  #       constraints:
  #         - "node.labels.index==0"

  rory-client-0:
    image: shanelreyes/rory:client
    container_name: rory-client-0
    hostname: rory-client-0
    ports:
      - 3001:3001
    environment:
      - NODE_ID=rory-client-0
      - NODE_PORT=3001
      - NODE_IP_ADDR=rory-client-0
      - SERVER_IP_ADDR=0.0.0.0
      - RORY_MANAGER_IP_ADDR=rory-manager-0
      - RORY_MANAGER_PORT=6000
      - LOGGER_NAME=rory-client-0
      - MAX_ITERATIONS=10
      - MAX_WORKERS=1
      - DEBUG =0
      - RELOAD=0
      - LIU_ROUND=1
      - TESTING=0
      - MICTLANX_TIMEOUT=${MICTLANX_TIMEOUT:-120}
      - MICTLANX_CLIENT_ID=${MICTLANX_CLIENT_ID:-rory-client-0}
      - MICTLANX_API_VERSION=${MICTLANX_API_VERSION:-3}
      - MICTLANX_ROUTERS=${MICTLANX_ROUTERS:-mictlanx-router-0:mictlanx-router-0:60666}
      - MICTLANX_DEBUG=${MICTLANX_DEBUG:-0}
      - MICTLANX_MAX_WORKERS:${MICTLANX_MAX_WORKERS:-4}
      - MICTLANX_PROTOCOL:${MICTLANX_PROTOCOL:-https}
      - LIU_SECURITY_LEVEL=128
      - SOURCE_PATH=/rory/source
      - SINK_PATH=/rory/sink
      - LOG_PATH=/rory/log
    volumes:
      - /rory/rory-client-0/source:/rory/source
      - /rory/rory-client-0/sink:/rory/sink
      - /rory/rory-client-0/log:/rory/log
      - /rory/mictlanx:/rory/mictlanx
      - /rory/keys:/rory/keys
    networks:
      - mictlanx
    deploy:
      placement:
        constraints:
          - "node.labels.index==1"

  rory-manager-0:
    image: shanelreyes/rory:manager
    container_name: rory-manager-0
    hostname: rory-manager-0
    ports:
      - 6000:6000
    environment:
      - NODE_ID=rory-manager-0
      - NODE_PORT=6000
      - NODE_IP_ADDR=rory-manager-0
      - SERVER_IP_ADDR=0.0.0.0
      - INIT_WORKERS=${INIT_WORKERS:-0}
      - WORKER_INIT_PORT=9000
      - DOCKER_IMAGE_NAME=shanelreyes/rory
      - DOCKER_IMAGE_TAG=worker
      - DEBUG=0
      - RELOAD=0
      - TESTING=0
      - MAX_RETRIES=10
      - LOAD_BALANCING=0
      - WORKER_MEMORY=2000000000
      - MICTLANX_SUMMONER_IP_ADDR=mictlanx-summoner-0
      - MICTLANX_SUMMONER_PORT=15000
      - MICTLANX_SUMMONER_MODE=docker
      - MICTLANX_SUMMONER_API_VERSION=2
      - LOGGER_NAME=rory-manager-0
      - SOURCE_PATH=/rory/source
      - SINK_PATH=/rory/sink
      - LOG_PATH=/rory/log
    volumes:
      - /rory/rory-manager-0/source:/rory/source
      - /rory/rory-manager-0/sink:/rory/sink
      - /rory/rory-manager-0/log:/rory/log
    networks:
      - mictlanx
    deploy:
      placement:
        constraints:
          - "node.labels.index==2"

  rory-worker-0:
      image: shanelreyes/rory:worker     # ← replace with your actual image name
      restart: unless-stopped
      environment:
        - RORY_DEBUG=${RORY_DEBUG:-1}
        - NODE_ID=${NODE_ID:-rory-worker-0}
        - NODE_PORT=${NODE_PORT:-9000}
        - NODE_INDEX=${NODE_INDEX:-0}
        - HOST_PORT=${HOST_PORT:-9000}
        - MAX_RETRIES=${MAX_RETRIES:-100}
        - RORY_MANAGER_PORT=${RORY_MANAGER_PORT:-6000}
        - RELOAD=${RELOAD:-0}
        - RORY_MANAGER_IP_ADDR=${RORY_MANAGER_IP_ADDR:-rory-manager-0}
        - NODE_IP_ADDR=${NODE_IP_ADDR:-rory-worker-0}
        - SERVER_IP_ADDR=${SERVER_IP_ADDR:-0.0.0.0}
        - DISTANCE=${DISTANCE:-EUCLIDEAN}
        - SOURCE_PATH=/rory/source
        - SINK_PATH=/rory/sink
        - LOG_PATH=/rory/log
        - MICTLANX_TIMEOUT=${MICTLANX_TIMEOUT:-120}
        - MICTLANX_CLIENT_ID=${MICTLANX_CLIENT_ID:-rory-worker-0}
        - MICTLANX_API_VERSION=${MICTLANX_API_VERSION:-3}
        - MICTLANX_ROUTERS=${MICTLANX_ROUTERS:-mictlanx-router-0:mictlanx-router-0:60666}
        - MICTLANX_DEBUG=${MICTLANX_DEBUG:-0}
        - MICTLANX_MAX_WORKERS:${MICTLANX_MAX_WORKERS:-4}
      ports:
        - "${RORY_WORKER_PORT:-9000}:${RORY_WORKER_PORT:-9000}"
      volumes:
        - /rory/rory-worker-0/source:/rory/source
        - /rory/rory-worker-0/sink:/rory/sink
        - /rory/rory-worker-0/log:/rory/log  
        - /rory/rory-worker-0/mictlanx:/rory/mictlanx
        - /rory/keys:/rory/keys
      networks:
        - mictlanx
networks:
  mictlanx:
    external: true
