services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "3030:80"

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}
    depends_on:
      - web
