services:
  db:
    image: postgres:15
    container_name: attendance_db
    environment:
      POSTGRES_DB: edutrack_attendance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  attendance-service:
    build: .
    container_name: attendance_service
    ports:
      - "8001:8000"
    environment:
      DB_NAME: edutrack_attendance
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
